"""
Table Retrieval Downstream Task (NQ-Tables)

This module implements table retrieval using dual projection heads
trained on frozen embeddings from any table encoder.

Task: Given a natural language question, retrieve the relevant table
from a corpus of 169,898 Wikipedia tables.

Dataset: NQ-Tables - 9,594 training queries, 1,068 dev queries
Source: Natural Questions dataset with Wikipedia tables

Embedding Setup:
- Query embeddings: Always generated by BERT (the text encoder)
- Table embeddings: Any table encoder (BERT, TaBERT, TAPAS, TabSketchFM, etc.)
- Hybrid mode (recommended): Table encoder embeddings + BERT table embeddings
  combined via concatenation. This bridges the modality gap between
  BERT query space and the table embedding space.

Usage:
    1. Create hybrid table embeddings (recommended for non-BERT encoders):
       python -m downstream_tasks.table_retrieval.create_hybrid_embeddings \\
           --base_variant column_mean \\
           --base_embeddings embeddings/column/tapas/nq_tables.pkl \\
           --bert_embeddings embeddings/column/bert/nq_tables.pkl \\
           --output_path embeddings/column/tapas_bert_hybrid/nq_tables.pkl

    2. Train projection head (query embeddings are always BERT):
       python -m downstream_tasks.table_retrieval.train \\
           --table_embeddings embeddings/column/tapas_bert_hybrid/nq_tables.pkl \\
           --table_id_mapping datasets/nq_tables/csv/table_id_to_csv.json \\
           --train_query_embeddings embeddings/table_retrieval/bert/queries_train.pkl \\
           --train_questions datasets/nq_tables/json/train.json \\
           --dev_query_embeddings embeddings/table_retrieval/bert/queries_dev.pkl \\
           --dev_questions datasets/nq_tables/json/dev.json \\
           --output_dir assets/checkpoints/table_retrieval/tapas_bert_hybrid

    3. Evaluate:
       python -m downstream_tasks.table_retrieval.evaluate \\
           --table_embeddings embeddings/column/tapas_bert_hybrid/nq_tables.pkl \\
           --table_id_mapping datasets/nq_tables/csv/table_id_to_csv.json \\
           --query_embeddings embeddings/table_retrieval/bert/queries_dev.pkl \\
           --questions_path datasets/nq_tables/json/dev.json \\
           --projection_head assets/checkpoints/table_retrieval/tapas_bert_hybrid/best_model.pt \\
           --output_path results/evaluation/table_retrieval/tapas_bert_hybrid_dev.json
"""

from .models.projection_head import DualProjectionHead, ProjectionHead
from .models.loss import BiEncoderNllLoss, InBatchNegativeLoss
from .evaluate import evaluate_retrieval

__all__ = [
    'DualProjectionHead',
    'ProjectionHead',
    'BiEncoderNllLoss',
    'InBatchNegativeLoss',
    'evaluate_retrieval',
]
